spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        default_schema: ${DATABASE_SCHEMA:gyuchanlee} # postgresql의 기본 스키마로 내 꺼 지정

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

# JWT 설정
jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}  # 60 min: 기본값 설정
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}  # 24 hours: 기본값 설정

# Cors 프론트 url 설정
cors:
  allowed-origins: https://nest-lecture-dodo-88013499747.asia-northeast2.run.app # todo 프론트 prod 환경 주소